name: "Setup Meshery"
description: "Deploy a Service Mesh on a KinD cluster using Meshery"
author: "DelusionalOptimist"
inputs:
  provider_token:
    description: "provider token to use"
  spec:
    description: "spec to run. possible values: SMI, SMP, istio-vet"
  service_mesh:
    # used for provisioning appropriate meshery-adatper
    description: "service mesh to use"
runs:
  using: "node12"
  main: "main.js"
